version: '3.8'

services:
  web:
    build: 
      context: ./services/web
    image: gunicorn_ja_img
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod

  nginx:
    image: nginx_ja_img
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
